name: ndc-http
version: "${CLI_VERSION}"
shortDescription: "CLI plugin for Hasura HTTP data connector"
homepage: https://github.com/hasura/ndc-http
hidden: true
platforms:
  - selector: darwin-arm64
    uri: "https://github.com/hasura/ndc-http/releases/download/${CLI_VERSION}/ndc-http-schema-darwin-arm64"
    sha256: "${MACOS_ARM64_SHA256}"
    bin: "hasura-ndc-http"
    files:
      - from: "./ndc-http-schema-darwin-arm64"
        to: "hasura-ndc-http"
  - selector: linux-arm64
    uri: "https://github.com/hasura/ndc-http/releases/download/${CLI_VERSION}/ndc-http-schema-linux-arm64"
    sha256: "${LINUX_ARM64_SHA256}"
    bin: "hasura-ndc-http"
    files:
      - from: "./ndc-http-schema-linux-arm64"
        to: "hasura-ndc-http"
  - selector: darwin-amd64
    uri: "https://github.com/hasura/ndc-http/releases/download/${CLI_VERSION}/ndc-http-schema-darwin-amd64"
    sha256: "${MACOS_AMD64_SHA256}"
    bin: "hasura-ndc-http"
    files:
      - from: "./ndc-http-schema-darwin-amd64"
        to: "hasura-ndc-http"
  - selector: windows-amd64
    uri: "https://github.com/hasura/ndc-http/releases/download/${CLI_VERSION}/ndc-http-schema-windows-amd64.exe"
    sha256: "${WINDOWS_AMD64_SHA256}"
    bin: "hasura-ndc-http.exe"
    files:
      - from: "./ndc-http-schema-windows-amd64.exe"
        to: "hasura-ndc-http.exe"
  - selector: linux-amd64
    uri: "https://github.com/hasura/ndc-http/releases/download/${CLI_VERSION}/ndc-http-schema-linux-amd64"
    sha256: "${LINUX_AMD64_SHA256}"
    bin: "hasura-ndc-http"
    files:
      - from: "./ndc-http-schema-linux-amd64"
        to: "hasura-ndc-http"
