linters:
  enable-all: true
  disable:
    - dupl
    - err113
    - lll
    - gocognit
    - exportloopref
    - funlen
    - godot
    - gofumpt
    - gomoddirectives
    - depguard
    - gosec
    - revive
    - cyclop
    - nestif
    - wsl
    - wrapcheck
    - varnamelen
    - exhaustive
    - exhaustruct
    - gocyclo
    - prealloc
    - ireturn
    - gochecknoglobals
    - gocyclo
    - godox
    - stylecheck
    - nilnil
    - maintidx
    - mnd
    - tagliatelle
    - goconst
    - noctx
    - unparam
    - recvcheck

linters-settings:
  nestif:
    # Minimal complexity of if statements to report.
    # Default: 5
    min-complexity: 10

issues:
  exclude-files:
    - ".*_test\\.go$"
