linters:
  enable-all: true
  disable:
    - err113
    - lll
    - gocognit
    - funlen
    - gomoddirectives
    - depguard
    - gosec
    - revive
    - cyclop
    - nestif
    - wsl
    - wrapcheck
    - varnamelen
    - exhaustive
    - exhaustruct
    - ireturn
    - gochecknoglobals
    - stylecheck
    - nilnil
    - mnd
    - tagliatelle
    - goconst
    - noctx
    - recvcheck

linters-settings:
  nestif:
    # Minimal complexity of if statements to report.
    # Default: 5
    min-complexity: 10

  gocritic:
    disabled-checks:
      - appendAssign
  gocyclo:
    min-complexity: 40

issues:
  exclude-files:
    - ".*_test\\.go$"
